<?php

namespace Lle\HelpBundle;

use Symfony\Component\HttpKernel\Bundle\Bundle;

class LleHelpBundle extends Bundle
{
    public function getContainerExtension()
    {
        return parent::getContainerExtension(); // TODO: Change the autogenerated stub
    }
}