services:
    _defaults:
        autowire: true
        public: false
        autoconfigure: true


    help.twig.help_extension:
        class: Lle\HelpBundle\Twig\HelpExtension
        tags:
            - { name: twig.extension }
        arguments:
            - "@doctrine.orm.default_entity_manager"